version: "3.9"

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart_db
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:15.2
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart_db_test
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/cart_db
      - ENVIRONMENT=PRODUCTION

volumes:
  postgres_data:
  postgres_test_data:
