package cart

const (
	SAME_SELLER_PROMOTION_ID             = 9909
	CATEGORY_PROMOTION_ID                = 5676
	TOTAL_PRICE_PROMOTION_ID             = 1232
	CATEGORY_PROMOTION_APPLICABLE_CAT_ID = 3003
	SAME_SELLER_PROMOTION_PERCENTAGE     = 0.10
	CATEGORY_PROMOTION_PERCENTAGE        = 0.05
	NUMBER_OF_PROMOTIONS                 = 3
)
