package item

const (
	MAX_DEFAULT_ITEMS           = 30
	MAX_DIGITAL_ITEMS           = 5
	MAX_UNIQUE_ITEMS            = 10
	DIGITAL_ITEM_CATEGORY_ID    = 7889
	MAX_PRICE_OF_CART           = 500000.0
	FURNITIRE_CATEGORY_ID       = 1001
	ELECTRONIC_CATEGORY_ID      = 3004
	VAS_ITEM_SELLER_ID          = 5003
	VAS_ITEM_CATEGORY_ID        = 3242
	MAX_VAS_ITEM_ON_SINGLE_ITEM = 3
)
